### ISSUE TITLE
Printstyles fehlen

### ISSUE THREAD

**Issue by jf-simon** [printmaps/printmaps#12]
Erst mal danke für das coole Tool.
Ich versuche es gerade lokal bei mir aufzusetzten.
Leider fehlen mir wie in der README beschrieben die printstyles.
Sie sind nicht im code.

Wo bekomme ich diese her?

Danke

Gruß Simon

**Comment by Klaus-Tockloth** [comment]
Die Printstyles stehen über die Webseite zur Verfügung:

http://printmaps-osm.de/de/nutzung.html

**Comment by jf-simon** [comment]
Danke für die schnelle Antwort. Habs gefunden.

Doch scheitere ich gerade noch daran, dass ich keine Anleitung für 
"aufsetzen einer (vollumfänglichen) Printmaps-Umgebung (mit DB)" finde.
Wie erstelle die die DB?
In der README finde ich leider keine genaueren Infos dazu.

Danke für die Hilfe.

Simon
