### ISSUE TITLE
Einstellung des Service auf: http://printmaps-osm.de/

### ISSUE THREAD

**Issue by PetersOtto** [printmaps/printmaps#14]
Es ist sehr schade, dass der Sevice auf `http://printmaps-osm.de/` eingestellt werden muss. Viele Karten habe ich nicht erstellen lassen aber zwei, drei mal war es wirklich sehr hilfreich! 

Danke das Sie sich so lange darum gekümmert haben!

**Comment by Klaus-Tockloth** [comment]
Printmaps lebt möglicherweise, ab Herbst/Winter 2024, in kleinerem Umfang (z. B. nur Europa, keine Höhenlinien, nur CLI-Clients, ...) auf einem anderen Server weiter.
