### ISSUE TITLE
Installationsanleitung angedacht?

### ISSUE THREAD

**Issue by PetersOtto** [printmaps/printmaps#15]
Hallo Herr Tockloth,
haben Sie geplant eine Installationsanleitung zu erstellen, bevor Sie den Service Ende des Jahres einstellen?
Ich würde `printmaps` gerne auf meinem eigenen kleinen Ubuntu/Apache Server, in meinem Heimnetz installieren. 
Mit den momentanen Erklärungen komme ich nicht klar, dafür bin ich weit genug im Thema.

**Comment by Klaus-Tockloth** [comment]
Möglicherweise zieht Printmaps im Herbst auf einen anderen Server um. In diesem Zusammenhang würde die Installationsanleitung auch auf den 'Prüfstand' gestellt.

Bis dahin wäre es günstig, konkrete Fragen bezüglich der Installation zu stellen.
