### ISSUE TITLE
Download always timeout

### ISSUE THREAD

**Issue by chrononaut1** [printmaps/printmaps#4]
Download map always timeout with error: 
> error <net/http: request canceled (Client.Timeout exceeded while reading body)> at io.Copy()

**Comment by Klaus-Tockloth** [comment]
The client timeout is set to 180 seconds. That's a very long time.

Questions:
- Why do think that the timeout message is a software issue?
- What's about your local system / network environment?
- Does it work from another system and/or network?
- What says the network trace?

**Comment by Klaus-Tockloth** [comment]
It seems that the client limits the download time to 180 seconds.

**Comment by Klaus-Tockloth** [comment]
Solved by removing the client timeout setting (new value = default = 0 = no timeout). 

See this commit: https://github.com/printmaps/printmaps/commit/f8a2e0f0c6db22e77d1c9354e4635f6613c392fb

@chrononaut1 : Thanks for reporting this issue.

**Comment by chrononaut1** [comment]
Hi @Klaus-Tockloth thank you for looking into this and for creating printmaps!
