### ISSUE TITLE
trying to replicate sample4, download error 412

### ISSUE THREAD

**Issue by natrius** [printmaps/printmaps#6]
I made my folder, downloaded the tool, copied the map.yaml and

  - `printmaps create`
  - `printmaps order`
  - `printmaps state`
  - `printmaps download`

That worked fine. Now i wantet to mark something or exclude something. So, i did the following:

Downloaded a json via https://api.openstreetmap.org/api/0.6/relation/86381/full.json and converted it to geojson via https://tyrasd.github.io/osmtogeojson/ and safed the resulting into an freilassing.json file. I then edited my my map.yaml with the following: 
```

# outmask freilassing
- Style: |
         <PolygonSymbolizer fill='#d9d9d9' />
         <PolygonPatternSymbolizer file='Printmaps_Hatch50_Grid_Grey_1.svg' alignment='global' />
         <LineSymbolizer stroke='dimgray' stroke-width='1' stroke-linecap='round' />
  SRS: '+init=epsg:4326'
  Type: ogr
  File: freilassing.geojson
  Layer: OGRGeoJSON
```
and made the following steps

  - `printmaps update`
  - `printmaps upload` (this should upload the geojson file?)
  - `printmaps order`
  - `printmaps state`
  - `printmaps download`

the upload results in 

```

url = http://printmaps-osm.de:8282/api/beta2/maps/
map ID = 1837e39f-2bd0-45ae-96d2-b38dd9a47e31
action = upload
```

and when downloading i get the following error

```
http response
-------------

HTTP/1.1 400 Bad Request
Content-Length: 479
Content-Type: application/vnd.api+json; charset=utf-8
Date: Thu, 26 Mar 2020 09:22:24 GMT

{
    "Errors": [
        {
            "ID": "1837e39f-2bd0-45ae-96d2-b38dd9a47e31",
            "Status": "412 Precondition Failed",
            "Code": "6004",
            "Source": {
                "Pointer": "SERVER: map build process"
            },
            "Title": "map build process not successful",
            "Detail": "OGR Plugin: Cannot open file 'freilassing.geojson'  encountered during parsing of layer 'userobject-0' in Layer at line 381"
        }
    ]
}

action result
-------------

expected status = '200 OK'
received status = '400 Bad Request'
FAILURE
```

it seems the file did not get uploaded. Do need to specify the file when using  `printmaps upload`?

Using Windows 10 right now.

Thanks for your service!

**Comment by printmaps** [comment]
The "UserFiles" section in map.yaml defines the files for upload. Example:

```
UserFiles:
- Baumberger-Ludgerusweg-Hauptweg.gpx
```

**Comment by natrius** [comment]
Ah, i completely missed that because i copied at first the .yaml from the schwarzplan+ :p

My fault. Danke für die rasche Hilfe!
